/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import bd.UserDAO;
import entity.User;

public class MainServer extends javax.swing.JFrame {
    int puertoServidorTCP = 1565;
    int puertoServidorUDP = 1566;
    /**
     * Creates new form MainServer
     */
    public MainServer() {
        initComponents();
        System.setProperty("java.net.preferIPv4Stack" , "true");
        try
        {
            s=new ServerSocket(puertoServidorTCP);
            slist=new ArrayList<>();
            nlist=new ArrayList<>();
            h=new HandleClientTCP();
            h.start();
            d=new DatagramSocket(puertoServidorUDP);
            t=new HandleClientUDP();
            t.start();
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        txtcmd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        sendToAll = new javax.swing.JCheckBox();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        namelist = new javax.swing.JTable();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_create = new javax.swing.JTextField();
        password_create = new javax.swing.JTextField();
        createUser = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username_modify = new javax.swing.JTextField();
        password_modify = new javax.swing.JTextField();
        modifyUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Servidor de llamadas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jInternalFrame1.setTitle("Enviar comandos a usuarios");
        jInternalFrame1.setVisible(true);

        txtcmd.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enviar a");

        cid.setEditable(false);
        cid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton2.setText("Ver comandos");

        sendToAll.setText("Enviar a todos");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcmd, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(sendToAll)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtcmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(sendToAll))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jInternalFrame2.setTitle("Usuarios conectados");
        jInternalFrame2.setVisible(true);

        namelist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuarios", "Estado", "Llamanda a"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        namelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namelistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(namelist);
        if (namelist.getColumnModel().getColumnCount() > 0) {
            namelist.getColumnModel().getColumn(0).setResizable(false);
            namelist.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        jInternalFrame3.setTitle("Crear usuario");
        jInternalFrame3.setVisible(true);

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        username_create.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        password_create.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        createUser.setText("Crear");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username_create, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_create))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(createUser)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createUser)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jInternalFrame4.setTitle("Modificar contraseña de usuario");
        jInternalFrame4.setVisible(true);

        jLabel4.setText("Usuario");

        jLabel5.setText("Nueva contraseña");

        username_modify.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        password_modify.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        modifyUser.setText("Modificar");

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username_modify))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(modifyUser))
                            .addComponent(password_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_modify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password_modify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modifyUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1)
                    .addComponent(jInternalFrame2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame3)
                    .addComponent(jInternalFrame4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            
            JOptionPane.showMessageDialog(null,"Cerrando el servidor...");
            Socket client_close;
            PrintWriter end;
            for(int x=0;x<slist.size();x++)
            {
                try{
                    client_close=slist.get(x);
                    end=new PrintWriter(client_close.getOutputStream(),true);
                    end.println("f73d5eab4fa29ffd6014aac366cc48de");
                }catch(Exception e){}
            }
            s.close();
            System.exit(0);
            
        } catch (IOException ex) {
            Logger.getLogger(MainServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void namelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namelistMouseClicked
        String data=String.valueOf(((DefaultTableModel)namelist.getModel()).getValueAt(namelist.getSelectedRow(), 0));
        cid.setText(data);
    }//GEN-LAST:event_namelistMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!txtcmd.getText().equals("") && !cid.getText().equals(""))
        {
            Socket cl=slist.get(Integer.parseInt(cid.getText()));
            try
            {
                out=new PrintWriter(cl.getOutputStream(),true);
                out.println("cmd:"+txtcmd.getText());
            }catch(Exception e){}
        }
        txtcmd.setText("");
        cid.setText("");
        txtcmd.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        User u=new User(username_create.getText(),password_create.getText());
        UserDAO udao=new UserDAO();
        try{
           udao.createUser(u); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_createUserActionPerformed

    /**
     * @param args the command line arguments
     */
    private ServerSocket s;
    private Socket c;
    private DatagramSocket d;
    private String username;
    private String password;
    private ArrayList<Socket> slist;
    private ArrayList<String> nlist;
    private BufferedReader brc;
    private PrintWriter out;
    private HandleClientTCP h;
    private HandleClientUDP t;
    private JSONObject json;
    private boolean a; 
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private javax.swing.JButton createUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyUser;
    private javax.swing.JTable namelist;
    private javax.swing.JTextField password_create;
    private javax.swing.JTextField password_modify;
    private javax.swing.JCheckBox sendToAll;
    private javax.swing.JTextField txtcmd;
    private javax.swing.JTextField username_create;
    private javax.swing.JTextField username_modify;
    // End of variables declaration//GEN-END:variables
    
    public void getCallHistoryList(){
    }
    public void getCallHistory(){
    }
    public void getConnectionsHistory(){
    }
    public void loadList(){
        while(namelist.getRowCount()>0)
        {
            ((DefaultTableModel)namelist.getModel()).removeRow(0);
        }
        int row=0;
        for(int x=0;x<nlist.size();x++)
        {
            if(!nlist.get(x).equals(""))
            {
                ((DefaultTableModel)namelist.getModel()).addRow(new Object[]{});
                ((DefaultTableModel)namelist.getModel()).setValueAt(nlist.get(x), row, 0);
                 row++;
            }
        }
    }
    
    class HandleClientTCP extends Thread
    {
        private int tid;
        public void run()
        {
            while(true)
            {
                try {
                    c=s.accept();
                    brc=new BufferedReader(new InputStreamReader(c.getInputStream()));
                    JSONObject json = new JSONObject(brc.readLine());
                    username=json.getString("username");
                    password=json.getString("password");
                    loginUser(username,password);
                    sendMessageToClient(c, "0", "0", "ok", "");
                    slist.add(c);
                    nlist.add(username);
                    loadList();
                    ProcessClient t=new ProcessClient(tid, username, c, password);
                    t.start();
                    tid++;
                } catch (Exception e) {
                    sendMessageToClient(c, "1", "0", "1", e.getMessage());
                }

            }
        }
        class ProcessClient extends Thread
        {
            private int id;
            private String username;
            private String password;
            private Socket c;
            private BufferedReader brc;
            public ProcessClient(int id,String username,Socket c, String password)
            {
                this.id=id;
                this.username=username;
                this.c=c;
                this.password=password;
            }
            public void run()
            {
                String msg;
                try{
                    brc=new BufferedReader(new InputStreamReader(c.getInputStream()));
                    loadList();
                    while((msg=brc.readLine())!=null)
                    {
                        json=new JSONObject(msg);
                        sendToAllClients("["+username+"] : "+msg);
                    }
                    sendToAllClients(username+ " Left Chat");
                nlist.set(id, "");
                loadList();
               }catch(Exception e){}
            }
        }
        public void sendToAllClients(String message)
        {
            Socket so;
            PrintWriter out;
            for(int x=0;x<slist.size();x++)
            {
                try{
                    so=slist.get(x);
                    out=new PrintWriter(so.getOutputStream(),true);
                    out.println(message);
                }catch(Exception e){}
            }
        }
        public void sendMessageToClient(Socket c, String estado, String tipo_operacion, String mensaje, String dato){
            try{
                json = new JSONObject();
                json.put("estado", estado);
                json.put("tipo_operacion", tipo_operacion);
                json.put("mensaje", mensaje);
                json.put("dato", dato);
                out=new PrintWriter(c.getOutputStream(),true);
                out.println(json.toString());
            }catch(Exception e){}
        }
        public void loginUser(String username, String password) throws Exception{
            UserDAO udao = new UserDAO();
            if (udao.login(username, password)){
                return;
            }
            throw new Exception("El usuario o la contraseña no son válidos");
        }
        public void initCall(){
        }
        public void endCall(){
        }
        public void sendMessageUserToUser(){
        }
    }
    
    class HandleClientUDP extends Thread
    {
        byte[] receiveData = new byte[1024];
        byte[] sendData = new byte[1024];
        public void run(){
            while (true) {
                try{
                    receiveData = new byte[1024];
                    DatagramPacket receivePacket=new DatagramPacket(receiveData, receiveData.length);
                    d.receive(receivePacket);
                    String datoRecibido = new String(receivePacket.getData());
                    json=new JSONObject(datoRecibido);
                    System.out.println(json.toString());
                    if (json.get("tipo_operacion").equals("1")){
                        InetAddress IPAddress = receivePacket.getAddress();
                        int port = receivePacket.getPort();
                        sendDatagramToUser(IPAddress, port,"0","1", nlist.toString());
                    }
                }catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}      
            }
        }
        public void sendDatagramToUser(InetAddress IPAddress, int port, String estado, String tipo_operacion, String dato){
            try{
                json = new JSONObject();
                json.put("estado", estado);
                json.put("tipo_operacion",tipo_operacion);
                json.put("mensaje","ok");
                json.put("dato",dato);
                sendData = json.toString().getBytes();
                DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, IPAddress,port);
                d.send(sendPacket);
            }catch(Exception e){}
        }
    }
}
